steps:
  # Step 1: Set up the Kubernetes credentials using gcloud
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'container'
      - 'clusters'
      - 'get-credentials'
      - 'devops-cluster'  # Your cluster name
      - '--region=us-central1'  # Your cluster region
    env:
      - 'CLOUDSDK_COMPUTE_REGION=us-central1'  # Ensure the region is correct
      - 'CLOUDSDK_COMPUTE_ZONE=us-central1'  # Ensure the zone is correct
      - 'CLOUDSDK_CONTAINER_CLUSTER=devops-cluster'  # Ensure the cluster name is correct

  # Step 2: Apply Kubernetes secrets
  - name: 'gcr.io/cloud-builders/kubectl'
    args:
      - 'apply'
      - '-f'
      - 'kubernetes/secrets.yaml'

  # Step 3: Build and push backend Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/evident-flame-400500/sum-backend:latest', './backend']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/evident-flame-400500/sum-backend:latest']

  # Step 4: Build and push frontend Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/evident-flame-400500/sum-frontend:latest', './frontend']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/evident-flame-400500/sum-frontend:latest']

  # Step 5: Apply all Kubernetes manifests in the `kubernetes/` directory
  - name: 'gcr.io/cloud-builders/kubectl'
    args:
      - 'apply'
      - '-f'
      - 'kubernetes/'

  # Step 6: Verify Kubernetes cluster info (checking if the credentials are valid)
  - name: 'gcr.io/cloud-builders/kubectl'
    args:
      - 'cluster-info'
    env:
      - 'CLOUDSDK_COMPUTE_REGION=us-central1'  # Ensure region is correct
      - 'CLOUDSDK_COMPUTE_ZONE=us-central1'  # Ensure zone is correct
      - 'CLOUDSDK_CONTAINER_CLUSTER=devops-cluster'  # Ensure cluster name is correct

options:
  logging: CLOUD_LOGGING_ONLY

images:
  - 'gcr.io/evident-flame-400500/sum-backend:latest'
  - 'gcr.io/evident-flame-400500/sum-frontend:latest'
