options:
  #machineType: 'E2_SMALL'  # Choose the smallest machine type
  logging: CLOUD_LOGGING_ONLY  # Use Cloud Logging only (no Cloud Storage bucket)

steps:
  # 1. Decrypt secrets using Cloud KMS via gcloud
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'kms'
      - 'decrypt'
      - '--keyring=YOUR_KEYRING_NAME'  # Replace with your KeyRing name
      - '--key=YOUR_KEY_NAME'           # Replace with your Key name
      - '--location=global'             # or your key's region (e.g., 'us-central1')
      - '--ciphertext-file=secrets.enc.yaml'  # Input encrypted file
      - '--plaintext-file=secrets.yaml'      # Output decrypted file

  # 2. Create Kubernetes secrets
  - name: 'gcr.io/cloud-builders/kubectl'
    args: ['apply', '-f', 'kubernetes/secrets.yaml']

  # 3. Build and push backend Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/evident-flame-400500/sum-backend:latest', './backend']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/evident-flame-400500/sum-backend:latest']

  # 4. Build and push frontend Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/evident-flame-400500/sum-frontend:latest', './frontend']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/evident-flame-400500/sum-frontend:latest']

  # 5. Apply all Kubernetes manifests in the `kubernetes/` directory
  - name: 'gcr.io/cloud-builders/kubectl'
    args: ['apply', '-f', 'kubernetes/']

images:
  - 'gcr.io/evident-flame-400500/sum-backend:latest'
  - 'gcr.io/evident-flame-400500/sum-frontend:latest'
