apiVersion: v1
kind: Service
metadata:
  name: sum-backend
spec:
  ports:
    - port: 5000
  selector:
    app: sum-backend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sum-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sum-backend
  template:
    metadata:
      labels:
        app: sum-backend
    spec:
      containers:
        - name: sum-backend
          image: gcr.io/$PROJECT_ID/sum-backend:latest
          ports:
            - containerPort: 5000
          env:
            - name: DB_HOST
              value: "sum-db-service"
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: POSTGRES_DB
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: POSTGRES_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: POSTGRES_PASSWORD
