apiVersion: v1
kind: Service
metadata:
  name: sum-db-service
spec:
  ports:
    - port: 5432
  selector:
    app: sum-db
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sum-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sum-db
  template:
    metadata:
      labels:
        app: sum-db
    spec:
      containers:
        - name: sum-db
          image: postgres:latest
          env:
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: POSTGRES_PASSWORD
          ports:
            - containerPort: 5432
